services:
  capstone:
    container_name: capstoneq4
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - db
    command: bash -c 'yarn migration:run && yarn dev'
  db:
    container_name: capstoneq4_database
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5432:5432
